lang = 'ENG'
if lang == 'ENG':
    start_text = 'start'
    help_text = 'help'
    back_text = 'Back'
    next_text = 'Next'
    NST_text = 'Style transfer'
    NST_cont_img_text = 'Load content image'
    NST_style_img_text = 'Load style image'
    settings_text = 'Settings'
    set_resolution_text = 'Set resolution'
    set_iterations_text = 'Set iterations number'
elif lang == 'RU':
    start_text = 'start'
    help_text = 'help'
    back_text = 'Назад'
    next_text = 'Далее'
    NST_text = 'Перенос стиля'
    NST_cont_img_text = 'Загрузить картинку контента'
    NST_style_img_text = 'Загрузить картинку стиля'
    settings_text = 'Настройки'
    set_resolution_text = 'Установить разрешение'
    set_iterations_text = 'Установить количество итераций'
